version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mathquest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 